openapi: 3.0.3
# 3.1.0 doesn't work on swagger-ui-express 4.6.2
info:
  title: MyBlog API
  description: API for MyBlog
  version: 1.0.0
tags:
  - name: post
    description: 포스트(게시물) API
  - name: category
    description: 카테고리 API
  - name: comment
    description: 댓글 API
  - name: user
    description: 유저 API
  - name: post_draft
    description: 임시 작성 포스트 API
paths:
  /:
    get:
      description: 블로그 메인 페이지
  /admin:
    get:
      description: 어드민 메인 페이지
  /users/signup:
    post:
      description: 회원 가입
      tags:
        - user
  /users/login:
    post:
      description: 로그인
      tags:
        - user
  /users/{user_email}:
    get:
      description: 유저 프로필 조회(기본 정보, 작성한 댓글)
      tags:
        - user
    put:
      description: 유저 프로필 수정(기본 정보)
      tags:
        - user
    delete:
      description: 회원 탈퇴(댓글 update 포함)
      tags:
        - user
  /categories:
    get:
      description: 카테고리 목록 조회
      tags:
        - category
      responses:
        "200":
          description: 카테고리 목록 반환
          content:
            application/x-www-urlencoded:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
              examples:
                data:
                  value: |
                    id=1&name=category1
                    &
                    id=2&name=category2
    post:
      description: 새 카테고리 생성
      tags:
        - category
  /categories/{name}:
    get:
      description: 특정 카테고리 포스트 조회
      tags:
        - category
    put:
      description: 특정 카테고리 수정
      tags:
        - category
    delete:
      description: 특정 카테고리 삭제
      tags:
        - category
  /posts:
    get:
      description: 전체 포스트 조회
      tags:
        - post
      responses:
        "200":
          description: 포스트 미리보기 반환
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  categoryId:
                    type: integer
              examples:
                data:
                  value: |
                    uuid=e67f1c05-5eb5-4ed7-af79-0e4bf4f8d4ba&title=title1&content=example+content&categoryId=1
                    &
                    uuid=9256e231-63dc-4ae5-899d-d471a6ac85ca&title=title2&content=example+2&categoryId=2
    post:
      description: 새 포스트 작성
      tags:
        - post
      responses:
        "201":
          description: 포스트가 성공적으로 작성됨
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successfully created a post
                  uuid:
                    type: string
                    example: 21e28bca-4a27-54f5-9c3e-370a6f83e2f5
  /posts/{post_uuid}:
    get:
      description: 특정 포스트 조회
      tags:
        - post
    put:
      description: 특정 포스트 수정
      tags:
        - post
    delete:
      description: 특정 포스트 삭제
      tags:
        - post
  /posts/{post_uuid}/comments:
    get:
      description: 특정 포스트 댓글 조회
      tags:
        - comment
    post:
      description: 특정 포스트 댓글 작성
      tags:
        - comment
      responses:
        "201":
          description: 댓글이 성공적으로 작성됨
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successfully created a comment
                  uuid:
                    type: string
                    example: 1d59dd1c-0808-5c74-b09c-77ad4021861f
  /posts/{post_uuid}/comments/{comment_uuid}:
    put:
      description: 댓글 수정
      tags:
        - comment
    delete:
      description: 댓글 삭제
      tags:
        - comment
  /posts/drafts:
    get:
      description: 모든 임시 저장 포스트 조회
      tags:
        - post_draft
    post:
      description: 새 포스트 임시 저장
      tags:
        - post_draft
      responses:
        "201":
          description: 포스트가 성공적으로 작성됨
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successfully created a drafted post
  /posts/drafts/{post_uuid}:
    get:
      description: 특정 임시 저장 포스트 정보 조회
      tags:
        - post_draft
    put:
      description: 특정 임시 저장 포스트 정보 수정
      tags:
        - post_draft
    delete:
      description: 특정 임시 저장 포스트 삭제
      tags:
        - post_draft
  /posts/drafts/{post_uuid}/publish:
    post:
      description: 특정 임시 저장 포스트 게시
      tags:
        - post_draft
      responses:
        "201":
          description: 임시 저장 포스트가 성공적으로 게시됨
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successfully published a post
